name: 'Deploy Docker Image to Heroku App'
author: 'Jean Carlos Taveras'
description: 'A simple action to build, push and deploy a Docker Image to your Heroku app.'
inputs:
  email:
    description: 'Email Linked to your Heroku Account'
    required: true
  api_key:
    description: 'Your Heroku API Key'
    required: true
  app_name:
    description: 'Your Heroku App Name'
    required: true
  dockerfile_path:
    description: 'Dockerfile path'
    required: true
  target_path:
    description: 'Target path (defaults to .)'
    required: false
  options:
    description: 'Optional build parameters'
    required: false
  process_type:
    description: 'Optional heroku process type (defaults to web)'
    required: false
branding:
  icon: package
  color: purple
runs:
  using: 'node12'
  main: 'dist/index.js'
