name: Build Changes
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm run build
      - name: Merge Build Changes
        run: |
          git config --global user.name "Build Changes Action"
          git config --global user.email "jctaveras@intellisys.com.do"
          git commit -am "Build Current Changes"
          git push
